version: '3.8'
# for local development
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    ports:
      - 8765:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - php
  mysql:
    image: mariadb:10.5
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8766:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    depends_on:
      - mysql
  php:
    build: 
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    volumes:
      - ./:/var/www/html
  composer:
    build: 
      context: .
      dockerfile: ./docker-compose/composer/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html